/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2026_bugatti_tourbillon.glb 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2026-bugatti-tourbillon-4f63f5a74611477989cefd9861b9784a
Title: 2026 Bugatti Tourbillon
*/



import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef, useEffect, useState } from 'react';
export function Bugatti_Sport(props) {
  const { nodes, materials } = useGLTF('/2026_bugatti_tourbillon.glb');

  console.log("Bugatti model loaded");

  const bodyMaterial = materials.santafek_body;


  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <group position={[0, 0.104, 0]}>
          <mesh geometry={nodes.bInterior_Geo_lodA_Interior_Geo_lodA_Bugatti_Tourbillon_2026InteriorA_Material_bBugatti_Tourbillon_2026InteriorA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026InteriorA_Material1} />
          <mesh geometry={nodes.bInterior_Geo_lodA_Interior_Geo_lodA_Bugatti_Tourbillon_2026InteriorA_Material_bBugatti_Tourbillon_2026InteriorA_Material1_0_1.geometry} material={materials.bBugatti_Tourbillon_2026InteriorA_Material1} />
        </group>
        <group position={[0, 0.104, 0]}>
          <mesh geometry={nodes.bPaint_Geo_lodA_Paint_Geo_lodA_Bugatti_Tourbillon_2026Paint_Material_bBugatti_Tourbillon_2026Paint_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Paint_Material1} />
          <mesh geometry={nodes.bPaint_Geo_lodA_Paint_Geo_lodA_Bugatti_Tourbillon_2026Paint_Material_col_2_0.geometry} material={materials.col_2} />
        </group>
        <group position={[0, 0.104, 0]}>
          <mesh geometry={nodes.bWindow_Geo_lodA_Window_Geo_lodA_Bugatti_Tourbillon_2026Window_Material_bBugatti_Tourbillon_2026Window_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Window_Material1} />
          <mesh geometry={nodes.bWindow_Geo_lodA_Window_Geo_lodA_Bugatti_Tourbillon_2026Window_Material_red_glass_0.geometry} material={materials.red_glass} />
        </group>
        <mesh geometry={nodes.bBadge_Geo_lodA_Badge_Geo_lodA_Bugatti_Tourbillon_2026BadgeA_Material_bBugatti_Tourbillon_2026BadgeA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026BadgeA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bBase_Geo_lodA_Base_Geo_lodA_Bugatti_Tourbillon_2026Base_Material_bBugatti_Tourbillon_2026Base_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Base_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bCarbon1_Geo_lodA_Carbon1_Geo_lodA_Bugatti_Tourbillon_2026Carbon1_Material_bBugatti_Tourbillon_2026Carbon1_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Carbon1_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bColoured_Geo_lodA_Coloured_Geo_lodA_Bugatti_Tourbillon_2026Coloured_Material_bBugatti_Tourbillon_2026Coloured_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Coloured_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bEngine_Geo_lodA_Engine_Geo_lodA_Bugatti_Tourbillon_2026EngineA_Material_bBugatti_Tourbillon_2026EngineA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026EngineA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleAlpha1_Geo_lodA_GrilleAlpha1_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha1A_Material_bBugatti_Tourbillon_2026GrilleAlpha1A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleAlpha1A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleAlpha2_Geo_lodA_GrilleAlpha2_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha2A_Material_bBugatti_Tourbillon_2026GrilleAlpha2A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleAlpha2A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleAlpha4_Geo_lodA_GrilleAlpha4_Geo_lodA_Bugatti_Tourbillon_2026GrilleAlpha4A_Material_bBugatti_Tourbillon_2026GrilleAlpha4A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleAlpha4A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleNoAlpha3_Geo_lodA_GrilleNoAlpha3_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha3A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha3A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha3A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleNoAlpha5_Geo_lodA_GrilleNoAlpha5_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha5A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha5A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha5A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleNoAlpha6_Geo_lodA_GrilleNoAlpha6_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha6A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha6A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha6A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleNoAlpha7_Geo_lodA_GrilleNoAlpha7_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha7A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha7A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha7A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bGrilleNoAlpha8_Geo_lodA_GrilleNoAlpha8_Geo_lodA_Bugatti_Tourbillon_2026GrilleNoAlpha8A_Material_bBugatti_Tourbillon_2026GrilleNoAlpha8A_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026GrilleNoAlpha8A_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bInteriorColourZone_Geo_lodA_InteriorColourZone_Geo_lodA_Bugatti_Tourbillon_2026InteriorColourZoneA_Material_bBugatti_Tourbillon_2026InteriorColourZoneA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026InteriorColourZoneA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bInteriorTillingColourZone_Geo_lodA_InteriorTillingColourZone_Geo_lodA_Bugatti_Tourbillon_2026InteriorTillingColourZoneA_Material_bBugatti_Tourbillon_2026InteriorTillingColourZoneA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026InteriorTillingColourZoneA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bLight_Geo_lodA_Light_Geo_lodA_Bugatti_Tourbillon_2026LightA_Material_bBugatti_Tourbillon_2026LightA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026LightA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bManufacturerPlate_Geo_lodA_ManufacturerPlate_Geo_lodA_Bugatti_Tourbillon_2026ManufacturerPlateA_Material_bBugatti_Tourbillon_2026ManufacturerPlateA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026ManufacturerPlateA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bSeatBelt_Geo_lodA_SeatBelt_Geo_lodA_Bugatti_Tourbillon_2026SeatBelt_Material_bBugatti_Tourbillon_2026Coloured_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Coloured_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bTextured_Geo_lodA_Textured_Geo_lodA_Bugatti_Tourbillon_2026TexturedA_Material_bBugatti_Tourbillon_2026TexturedA_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026TexturedA_Material1} position={[0, 0.104, 0]} />
        <mesh geometry={nodes.bWindowInside_Geo_lodA_WindowInside_Geo_lodA_Bugatti_Tourbillon_2026WindowInside_Material_bBugatti_Tourbillon_2026Window_Material1_0.geometry} material={materials.bBugatti_Tourbillon_2026Window_Material1} position={[0, 0.104, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/2026_bugatti_tourbillon.glb')
